services:
  signalzxh-blog:
    build:
      context: .
      target: final
    container_name: signalzxh-blog
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static
      - ./.env:/app/.env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_DB: ${REDIS_DB}
    mem_limit: 200m
    memswap_limit: 200m

  mysql:
    image: mysql:9.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    mem_limit: 256m
    memswap_limit: 256m

  redis: 
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
    mem_limit: 64m
    memswap_limit: 64m
volumes:
  mysql-data:
  redis-data: